#!/usr/bin/env python3

import sys
import math

def print_help():
    print("USAGE\n    ./101pong x0 y0 z0 x1 y1 z1 n\n\n")
    print("DESCRIPTION")
    print("    x0  ball abscissa at time t - 1")
    print("    y0  ball ordinate at time t - 1")
    print("    z0  ball altitude at time t - 1")
    print("    x1  ball abscissa at time t")
    print("    x0  ball ordinate at time t")
    print("    x0  ball altitude at time t")
    print("    n   time shift (greater than or equal to zero, integer)")

def Pong(argv):
    if argv[0] == "-h":
        print_help()
        sys.exit(0)
    if len(argv) != 7:
        sys.exit(84)

    x0, y0, z0, x1, y1, z1, n = map(float, argv)
    n = int(n)
    X = x1 - x0
    Y = y1 - y0
    Z = z1 - z0
    print("The velocity vector of the ball is:")
    print("({:.2f}, {:.2f}, {:.2f})".format(X, Y, Z))
    print("At time t + {}, ball coordinates will be:".format(n))
    coor_X = X * n + x1
    coor_Y = Y * n + y1
    coor_Z = Z * n + z1
    print("({:.2f}, {:.2f}, {:.2f})".format(coor_X, coor_Y, coor_Z))
    if (z1 >= 0 and coor_Z < 0):
        print("The incidence angle is:")
        norme = math.sqrt(X ** 2 + Y **2 + Z ** 2)
        angle = math.asin(abs(Z) / norme)
        angle_degrees = math.degrees(angle)
        angle_degrees = min(angle_degrees, 90)
        print("{:.2f} degrees".format(angle_degrees))
    else :
        print("The ball won't reach the paddle")

def main(args):
    Pong(args)

if  __name__ == "__main__":
    main(sys.argv[1:])